name: Run Postman API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Newman (Postman CLI)
      run: npm install -g newman

    - name: Run Postman Collection
      run: |
        newman run AI_Product_API_Testing.postman_collection.json \
          --env-var "baseUrl=https://api-with-bugs.practicesoftwaretesting.com" \
          --reporters cli
